import {auditBonuses,processDailyBonus,parseReport} from './parser.js';
const Deposit Request History QRPay=`| | **User Name** | **From Bank** | **To Bank** | **Amount** | **Reference** | **RRN** | **Date** | **Payment Method** | **Status** | **Invoice** | **Status Date** | **Remark** | **Edited By** |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|1|BEB\\@Sf0810|DANA<br>Sultan Faiz Alfalah<br>08**19087***|PrabuPay<br>mariobola_oauser<br>id|**500.000**|17900064366235456||22/09/2026 12:00:37 AM|QR Pay|Confirmed|View|22/09/2026 12:01:23 AM||QRPay User|
|2|BEB\\@Copler27|BCA<br>Ismail Nadhom<br>1012091804|PrabuPay<br>mariobola_oauser<br>id|**200.000**|17900064916815972||22/09/2026 12:01:33 AM|QR Pay|Confirmed|View|22/09/2026 12:02:11 AM||QRPay User|
|3|BEB\\@msptra55|GO PAY<br>Muhamadsaputra<br>08**98013***|PrabuPay<br>mariobola_oauser<br>id|**60.000**|17900064936129568||22/09/2026 12:01:33 AM|QR Pay|Confirmed|View|22/09/2026 12:03:00 AM||QRPay User|
|4|BEB\\@Wakleng123|BNI<br>Sufriyadi<br>1888017846|PrabuPay<br>mariobola_oauser<br>id|**300.000**|17900065612387334||22/09/2026 12:02:41 AM|QR Pay|Confirmed|View|22/09/2026 12:03:19 AM||QRPay User|
|5|BEB\\@bily12|DANA<br>pipit<br>08**15990***|PrabuPay<br>mariobola_oauser<br>id|**50.000**|17900065329696942||22/09/2026 12:02:14 AM|QR Pay|Confirmed|View|22/09/2026 12:03:33 AM||QRPay User|`;
const Deposit Request History=`| ** ** | **User Name** | **From Bank** | **To Bank** | **Amount** | **Date** | **Payment Method** | **Status** | **Status Date** | **Remark** | **Edited By** |
|---|---|---|---|---|---|---|---|---|---|---|---|
|1|BEB\\@Sf0810|DANA<br>Sultan Faiz Alfalah<br>08**19087***|SCB<br>SCB A BONUS DEPOSIT HARIAN<br>01|**25.000**|22/09/2026 12:03:28 AM|Agent Deposit|Confirmed|22/09/2026 12:03:57 AM||beb\\@mario08|
|2|BEB\\@Copler27|BCA<br>Ismail Nadhom<br>1012091804|SCB<br>SCB A BONUS DEPOSIT HARIAN<br>01|**10.000**|22/09/2026 12:03:45 AM|Agent Deposit|Confirmed|22/09/2026 12:03:57 AM||beb\\@mario08|
|3|BEB\\@msptra55|GO PAY<br>Muhamadsaputra<br>08**98013***|SCB<br>SCB A BONUS DEPOSIT HARIAN<br>01|**3.000**|22/09/2026 12:03:53 AM|Agent Deposit|Confirmed|22/09/2026 12:03:58 AM||beb\\@mario08|
|4|BEB\\@Wakleng123|BNI<br>Sufriyadi<br>1888017846|SCB<br>SCB A BONUS DEPOSIT HARIAN<br>01|**15.000**|22/09/2026 12:04:12 AM|Agent Deposit|Confirmed|22/09/2026 12:04:24 AM||beb\\@mario08|
|5|BEB\\@bily12|DANA<br>pipit<br>08**15990***|SCB<br>SCB A BONUS DEPOSIT HARIAN<br>01|**2.500**|22/09/2026 12:04:21 AM|Agent Deposit|Confirmed|22/09/2026 12:04:28 AM||beb\\@mario08|`;
const $=s=>document.querySelector(s); const money=n=>new Intl.NumberFormat('id-ID').format(n||0); const statusClass=s=>s==='SESUAI'?'good':s==='LEBIH BONUS'?'warn':(s==='KEKURANGAN BONUS'||s.includes('BELUM')||s.includes('BLOKIR'))?'bad':'muted';
let checkRows=[], inputRows=[];
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function renderCheck(){const tb=$('#checkTable tbody'); const visible=checkRows.filter(r=>!r.hidden); const hidden=checkRows.filter(r=>r.hidden); $('#checkSummary').textContent=`${visible.length} tampil • ${hidden.length} disembunyikan • ${checkRows.filter(r=>r.doubleBonus).length} terdeteksi double bonus`;
 tb.innerHTML=visible.length?visible.map(r=>`<tr><td><b>${escapeHtml(r.username)}</b></td><td>${money(r.depositAmount)}</td><td>${money(r.expectedBonus)}</td><td>${money(r.givenBonus)}</td><td><span class="status ${statusClass(r.status)}">${escapeHtml(r.status)}</span></td><td><span class="pill ${r.doubleBonus?'yes':'no'}">${r.doubleBonus?'YA':'TIDAK'}</span></td><td>${escapeHtml(r.remarkStatus)}</td><td>${escapeHtml(r.depositDate)}</td><td><button class="hide-btn" data-hide-check="${checkRows.indexOf(r)}">Sembunyikan</button></td></tr>`).join(''):'<tr><td colspan="9" class="empty">Tidak ada hasil yang tampil.</td></tr>';
 $('#hiddenCheck').innerHTML=hidden.length?`<div class="hidden-title">Data disembunyikan (${hidden.length})</div><div class="hidden-items">${hidden.map(r=>`<div class="hidden-item"><b>${escapeHtml(r.username)}</b><span>Deposit ${money(r.depositAmount)} • ${escapeHtml(r.status)}</span><button class="hide-btn" data-show-check="${checkRows.indexOf(r)}">Munculkan</button></div>`).join('')}</div>`:'';}
function renderInput(){const tb=$('#inputTable tbody'); const visible=inputRows.filter(r=>!r.hidden); const hidden=inputRows.filter(r=>r.hidden); $('#inputSummary').textContent=`${visible.length} baris tampil • ${hidden.length} disembunyikan • ${inputRows.filter(r=>r.doubleBonus).length} baris berada pada username yang muncul lebih dari sekali`;
 tb.innerHTML=visible.length?visible.map(r=>`<tr><td><b>${escapeHtml(r.username)}</b></td><td>${money(r.amount)}</td><td>${escapeHtml(r.date)}</td><td><span class="pill ${r.doubleBonus?'yes':'no'}">${r.doubleBonus?'YA':'TIDAK'}</span></td><td><button class="hide-btn" data-hide-input="${inputRows.indexOf(r)}">Sembunyikan</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">Tidak ada data yang tampil.</td></tr>';
 $('#hiddenInput').innerHTML=hidden.length?`<div class="hidden-title">Data disembunyikan (${hidden.length})</div><div class="hidden-items">${hidden.map(r=>`<div class="hidden-item"><b>${escapeHtml(r.username)}</b><span>${money(r.amount)} • ${escapeHtml(r.date)}</span><button class="hide-btn" data-show-input="${inputRows.indexOf(r)}">Munculkan</button></div>`).join('')}</div>`:'';}
$('#processCheck').onclick=()=>{const qr=$('#qrText').value.trim(), h=$('#historyText').value.trim(); if(!qr||!h){$('#checkSummary').textContent='Dua sumber wajib diisi.';return;} checkRows=auditBonuses(qr,h,{rate:Number($('#rate').value)/100,windowHours:Number($('#window').value)});renderCheck();};
$('#clearCheck').onclick=()=>{$('#qrText').value='';$('#historyText').value='';checkRows=[];renderCheck();};
$('#processInput').onclick=()=>{const h=$('#inputHistory').value.trim(); if(!h){$('#inputSummary').textContent='Data Deposit Request History wajib diisi.';return;} inputRows=processDailyBonus(h,{sort:$('#sort').value}).rows;renderInput();};
$('#copyInput').onclick=async()=>{const txt=inputRows.filter(r=>!r.hidden).map(r=>`${r.username}\t${r.amount}`).join('\n'); if(!txt)return; await navigator.clipboard.writeText(txt);$('#inputSummary').textContent='Hasil 2 kolom berhasil disalin ke clipboard.';};
document.addEventListener('click',e=>{const b=e.target.closest('[data-hide-check]');if(b){const row=checkRows[Number(b.dataset.hideCheck)];if(row)row.hidden=true;renderCheck();} const bs=e.target.closest('[data-show-check]');if(bs){const row=checkRows[Number(bs.dataset.showCheck)];if(row)row.hidden=false;renderCheck();} const c=e.target.closest('[data-hide-input]');if(c){const row=inputRows[Number(c.dataset.hideInput)];if(row)row.hidden=true;renderInput();} const cs=e.target.closest('[data-show-input]');if(cs){const row=inputRows[Number(cs.dataset.showInput)];if(row)row.hidden=false;renderInput();} const ex=e.target.closest('[data-example]');if(ex){const type=ex.dataset.example;if(type==='qr')$('#qrText').value=Deposit Request History QRPay;else {$('#historyText').value=Deposit Request History;$('#inputHistory').value=Deposit Request History;}}});
document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('#tab-'+btn.dataset.tab).classList.add('active');});
function tick(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('id-ID',{hour12:false})+' WIB';}tick();setInterval(tick,1000);
